### ISSUE TITLE
[BUG] 1px error when packing images

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [oblivioncth/Stexatlaser#12]
With the following images packed, some of the images have its size 64x63, instead of 63x63.
[wokey_inventoryimages.zip](https://github.com/oblivioncth/Stexatlaser/files/12287005/wokey_inventoryimages.zip)

**Comment by oblivioncth** [comment]
~~Just to clarify the issue, it seems like it's the 64x64 images that end up with 64x63, not the 63x63 images, correct?~~ NVM, I see that they're all 64x64

Secondly, just for context, are you actual having issues with parts of your textures getting clipped in game? Or did you just happen to load the atlas into a `.tex` viewer and notice the slightly different dimensions? Some tools interpret the element UV coordinates differently.

**EDIT:** If you saw the rest of the original comment, disregard it as there may be a minor inaccuracy in the generated textures due to a misunderstanding of mine in regards to a fine detail when mapping pixel coordinates to UV coordinates.

Regardless, the question still stands though, do you notice actual issues in game?

**Comment by ZzzzzzzSkyward** [comment]
I see from TEX Tool that it is 64x63. I know such error may be inperceptible, but all other tools like ktech, ztools and Texture and Atlas Packer generates 63x63 tex, which may indicate that they all use the same algorithm. However, this can result in an incompatibility between STex and other tools.

**Comment by ZzzzzzzSkyward** [comment]
Source Image
![Snipaste_2023-08-09_13-52-12](https://github.com/oblivioncth/Stexatlaser/assets/55184223/0d694974-d539-40f5-994f-c646b5abe0fc)
64x64 png
![1](https://github.com/oblivioncth/Stexatlaser/assets/55184223/912cb971-64f6-4b4f-b980-a8cfa86cf116)
STex in game, compiled with 4 same png files, displaying the first image
![Snipaste_2023-08-09_13-49-01](https://github.com/oblivioncth/Stexatlaser/assets/55184223/6da06bd8-6ac6-4d44-ab68-2338ab9f6235)
ztools in game
![Snipaste_2023-08-09_13-49-17](https://github.com/oblivioncth/Stexatlaser/assets/55184223/7288b817-51b9-4b80-a899-73fecfe514cd)
You can see ztools in more accurate than STex by 1px at the top left pixel.

**Comment by oblivioncth** [comment]
Thanks for the empirical data. Funny enough I was also comparing results with Atlas Packer (if you're referring to the one by Kzicor) but that actually shows the elements as 63x63 in TEXTool.

Anyway, I tweaked/fixed the process to better handle the UV mapping according to standard practice. Let me know what you think of this build: ~~https://github.com/oblivioncth/Stexatlaser/actions/runs/5810534307~~

Don't have time at the moment to analyze the results in-game, but all elements now show as 64x64 in TEXTool.

**Comment by ZzzzzzzSkyward** [comment]
> Thanks for the empirical data. Funny enough I was also comparing results with Atlas Packer (if you're referring to the one by Kzicor) but that actually shows the elements as 63x63 in TEXTool.
> 
> Anyway, I tweaked/fixed the process to better handle the UV mapping according to standard practice. Let me know what you think of this build: https://github.com/oblivioncth/Stexatlaser/actions/runs/5810534307
> 
> Don't have time at the moment to analyze the results in-game, but all elements now show as 64x64 in TEXTool.

I thought you misunderstood?  63x63 is the correct size in TEX Tool. Thus images can be converted back to 64x64. STex is adding a 1px border somehow.

**Comment by oblivioncth** [comment]
Ah, I missed the first part of your response.

That surprises me as I'd expect that with a good mapping it should be 64x64 in both systems, but let me investigate a bit further.

**Comment by ZzzzzzzSkyward** [comment]
This is the repo of ztools: https://gitlab.com/Zarklord/ztools

**Comment by oblivioncth** [comment]
> This is the repo of ztools: https://gitlab.com/Zarklord/ztools

Thanks, I somehow forgot that was open source, and of course that's about as close to an official source for how to handle this translation as you can get given it's by Zarklord.

I will compare my current output with ztool (and inspect its source if there's a difference) a bit later. For now, I realized there was a minor mistake in my fix due to a quirk with QRect vs QRectF I hadn't accounted for. I've corrected the issue such that the fix is what I had original intended and updated the correction branch. All of the sample textures now do show as 63x63 in TEXTool and have UV values that are extremely close (though not technically identical) to the output of Atlas Packer.

I'd be curious to see the result of your prior test with this now corrected build if you have the time: https://github.com/oblivioncth/Stexatlaser/actions/runs/5822877122

I'm also going to double check how TEXTool is determining the size of atlas elements as it's more or less converting UV-coordinates to pixel-coordinates the same way I do, and so it really should be showing 64x64 and not 63x63. There's likely a bug there as well.

**EDIT:** I compared the atlas key created by Stex to the one created by ztools and the UV values are practically identical (no difference until the **8th** decimal place). I may poke around the source to see what the extremely tiny difference is about, but in practice the atlases should be functionally the same. Doesn't seem like ztools can break apart and atlas (unless I'm missing something), so there's no way to compare against it for that, though there's no reason it should be different.

I also updated my fork of DSTTools (TEXTool) to show the proper size of atlas elements as it was indeed off-by-one. For example it was using `right - left` instead of `(right - left) + 1`.

**Comment by ZzzzzzzSkyward** [comment]
Thank you! From what I can see, this issue is solved. By the way, I would appreciate it if you add a param that defines the width and height to be power of 2, like that in Texture and Atlas Packer. It is only useful when generating a minimap icon atlas.

**Comment by oblivioncth** [comment]
> Thank you! From what I can see, this issue is solved. By the way, I would appreciate it if you add a param that defines the width and height to be power of 2, like that in Texture and Atlas Packer. It is only useful when generating a minimap icon atlas.

Awesome.

Just to make sure I understand your request, I'm guessing you mean an option to force the atlas to be **square** right? As is, the width and height are always a power of 2, but they are not necessarily the same power of two, as a rectangle will be used if it fits all textures.

**Comment by ZzzzzzzSkyward** [comment]
> Awesome.
> 
> Just to make sure I understand your request, I'm guessing you mean an option to force the atlas to be **square** right? As is, the width and height are always a power of 2, but they are not necessarily the same power of two, as a rectangle will be used if it fits all textures.

Exactly as Texture and Atlas Packer does, not necessarily square, but power of 2. <del>This is because DST has an assert that a minimap atlas must be that. When I used STex to generate minimap atlas, the game crashed. At first I suspect STex gave wrong coordinates, but then I realized it is because not power of 2.</del>
Seems that I cannot reproduce the crash, the atlas given by STex is already power of 2. However, the atlas seems cannot be read by DST. When I used the atlas from STex v0.2, the icons are black. I am more confused now.
![Snipaste_2023-08-11_21-41-39](https://github.com/oblivioncth/Stexatlaser/assets/55184223/ea29b262-05d5-4d99-9432-18d92b8f551d)

**Comment by oblivioncth** [comment]
I would like to figure out what's going on with this before pushing another release, since what I meant was that Stex already strictly adheres to power-of-2 output as you noticed, and so I don't know why this doesn't work for mini-maps as is.

If you are able, feel free to create a new issue regarding this problem and include sample texture icons and the atlas generated with them that doesn't work in-game when using Stex (the latest build above), but does work when generated with another tool (e.g. ztools) so that I can compare the atlases to each other.

I really appreciate your help looking into these issues as I don't currently have the game installed and most of my DST stuff is packed away in an archive somewhere.
