### ISSUE TITLE
[Feature] Single tex conversion

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [oblivioncth/Stexatlaser#18]
An experiment demonstrates that STex is the only program that faithfully keeps the color and transparency of transparent pixels in a tex file.
So I'd appreciate it if you can support single tex conversion. It will be useful in converting animation.

![diff](https://github.com/oblivioncth/Stexatlaser/assets/55184223/bc67e520-dd66-4e6d-900e-be665323a8a7)

**Comment by oblivioncth** [comment]
Interesting, I wouldn't have guessed the others had that issue.

Technically, you can convert a single image by just using pack with only 1 file in the specified folder; however, would it perhaps be more convenient to have a separate command that converts to/from TEX with the source image as-is (i.e. no atlasing/deatlasing), creates no key (xml), and has you point directly to the file in question with the input switch instead of a containing folder?

It should be fairly trivial to add this so I'll pretty much do it regardless.

**Comment by oblivioncth** [comment]
@ZzzzzzzSkyward Sorry it took so long, but this is in the latest release now.
