### ISSUE TITLE
[bug] Atlas element names missing ".tex" extension

### ISSUE THREAD

**Issue by RebeccaStevens** [oblivioncth/Stexatlaser#2]
The generated atlas file doesn't append the `.tex` extension to elements' name; thus prevent the game form being able to load the texture. Manually fixing this makes the textures display correctly.

Actual output:
```xml
<Element name="elementname" ... />
```

Expected output:
```xml
<Element name="elementname.tex" ... />
```

**Comment by oblivioncth** [comment]
This one is a little more interesting. Since I'm somewhat new to modding DST, I don't want to assert things that are untrue, but I think I understand this well enough. There is a little backstory... (tl;dr at the bottom)

When inspecting other people's mods to help figure out how the mod API works, it always annoyed me seeing situations like this:

Files: myatlas.tex, myatlas.xml

myatlas.xml:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Atlas>
    <Texture filename="myatlas.tex"/>
    <Elements>
        <Element name="myatlas.tex" u1="..." u2="..." v1="..." v2="..."/>
        <Element name="myatlas-blue.tex" u1="..." u2="..." v1="..." v2="..."/>
        <Element name="myatlas-green.tex" u1="..." u2="..." v1="..." v2="..."/>
...
```
Lua:
`inst.MiniMapEntity:SetIcon("myatlas.tex")`

Because I'd wonder: Does this call refer directly to the TEX file itself, and for mini-map icons it always just reads the first element and ignores the others, or is it actually referring to the first element. It was impossible to know since they had the same name. After some time I came to the conclusion that it is referring to the element name and not the file directly, especially since the atlas is already loaded with `AddMinimapAtlas(myatlas.xml)` (why would the key need to be loaded by name if the TEX was just going to be referenced directly and assume they key name using the TEX name), but regardless it still bugged me that the names were the same.

----

While yes, in my own mods I could just make sure that the file name and element names are always different, I realized something: The element names are nothing more than labels, heck they're even just string XML elements that act as identifiers. It isn't like those original images were TEX files themselves, they often were more standard image formats. From what I understand, including the extensions is simply standard practice that everyone is used to. You can even see in some of Klei's keys the elements have names ending with a ".png" extension from probably an earlier time when they packed atlases directly from PNG instead of (what I'm guessing they do now) having converted them to TEX first and then packing them with custom tools.

Therefore, since the names are just identifiers for a portion of the image, a literal "Element Name" and not an image name, I felt that having an extension associated with them was a bit odd since in no way are they referring to actual files once packed. It would be like if you made an excel chart about weather patterns from raw data you recorded in weather_data.csv and instead of giving the chart a title like "Observed Weather Data" you gave it a title of "weather_data.csv". You would still know what you were referring to but its less clear when standing alone IMO.

So, in the first mod I'm improving after making this tool, I organize my sprites like so (before packing):
```
.craftmenu
|-- my_entity.png
|-- my_entity_skin1.png
|-- my_entity_skin2.png
|-- ...
```

and then in the mod do:
```lua
local statuerecipe = AddRecipe("myentity",
{  Ingredient(...)},
RECIPETABS.SCIENCE,
tech..,
"placer...",
1.5,
nil,
nil,
nil,
"images/inventoryimages/craftmenu.xml",
"my_entity") -- Extensionless element name
statuerecipe.sortkey = -99
statuerecipe.skinnable = true
... -- Add skins
```

and it works.

HOWEVER, while I haven't been able to get back to it for a while, I do have a weird issue where a few mini-map icons are being displayed as black squares even though I see no reason for that to be the case. I wonder if Klei screwed up the API somewhere and in some sections it is hard-coded to expect an extension, with this design choice then perhaps being related.

**Please test for me if you *don't* manually add '.tex' to the output atlas key, and change your element references in LUA so that they match and don't have a '.tex' suffix either, if it then also works that way.**

**Comment by RebeccaStevens** [comment]
I fully agree with you on this that the extension shouldn't be needed.
However, there are parts of Klei code that will automatically append the ".tex" extension if it's not already present. Because of this, I think it's always best to just add the extension to avoid possible breakages.

Quick findings:

- Doing a quick search, there are 147 locations in Klei code where ".tex" is appended to the end of a string.
- With a mod's icon, it needs to point to an actual file as Klei code checks the file exists with `softresolvefilepath`.
	- This also means that the mod icon cannot be in a subdirectory (unless the label also includes this, maybe?)

I'll do some more testing and see if I find out any more useful info.

**Comment by oblivioncth** [comment]
Interesting, I was a bit afraid of something like that, but wow I didn't anticipate how widespread it was.

I guess I'll sacrifice neatness for compatibility haha. Extension it is.

I really appreciate the assistance.

EDIT:
While in the end it's probably better to just play it safe, see if you can make sure this definitely affects atlas elements and isn't just for the TEX files themselves.

**Comment by oblivioncth** [comment]
While I am interested in the specifics of this, I did confirm you were correct with your example in that the modicon.xml element must have a ".tex" extension or else it breaks, which is good enough for me to enforce this behavior.

Added in [32829a1](https://github.com/oblivioncth/Stexatlaser/commit/32829a10d6b3df13a432f6decc48a18d892cb7a8)
