### ISSUE TITLE
GLIBC 2.33 isn't easily available for Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by RebeccaStevens** [oblivioncth/Stexatlaser#3]
Would it be easily possible for this program to downgrade it's glibc dependency to version 2.31 as that is what's on ubuntu lts? This will make it much easier for users to use the program.

https://launchpad.net/ubuntu/+source/glibc/

**Comment by oblivioncth** [comment]
Absolutely.

Sorry, I should have thought of this in the first place, but I don't do much Linux development and the C++ redistributables don't update as often on Windows and I'm not readily familiar with some aspects of dependencies with Linux.

I may need to spin another VM for this though because it looks like you can't simply target a lower lib version with g++. There's a few other methods I'll check first though.

**Comment by oblivioncth** [comment]
Hmmm, yea this is one thing that drives me a little nuts.

It seems the main two ways to do this otherwise are to either compile your own Glibc, or to use metafunctions to force a certain lib version for specific functions, which in this case would require modifying my source, and is outright unrealistic given I depend on Qt.

So in the end the easiest, but still tedious way is to make another Ubunut VM on 20.04 LTS (which I was on until I updated right before doing this -_-) and build there.

I'll have to install all the dependencies and rebuild Qt as well, but I mostly have this in scripts so it won't be too bad, it will just take some time.

**Comment by oblivioncth** [comment]
Resolved with https://github.com/oblivioncth/Stexatlaser/releases/tag/v0.2.0.1
